// Code generated by "requestgen -method POST -url /fapi/v1/order -type FuturesPlaceOrderRequest -responseType .FuturesOrderResponse"; DO NOT EDIT.

package binanceapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"sync"
)

/*
 * Symbol sets
 */
func (f *FuturesPlaceOrderRequest) Symbol(symbol string) *FuturesPlaceOrderRequest {
	f.symbol = symbol
	return f
}

/*
 * Side sets
 */
func (f *FuturesPlaceOrderRequest) Side(side SideType) *FuturesPlaceOrderRequest {
	f.side = side
	return f
}

/*
 * PositionSide sets
 */
func (f *FuturesPlaceOrderRequest) PositionSide(positionSide PositionSide) *FuturesPlaceOrderRequest {
	f.positionSide = &positionSide
	return f
}

/*
 * OrderType sets
 */
func (f *FuturesPlaceOrderRequest) OrderType(orderType FuturesOrderType) *FuturesPlaceOrderRequest {
	f.orderType = orderType
	return f
}

/*
 * TimeInForce sets
 */
func (f *FuturesPlaceOrderRequest) TimeInForce(timeInForce TimeInForceType) *FuturesPlaceOrderRequest {
	f.timeInForce = &timeInForce
	return f
}

/*
 * Quantity sets
 */
func (f *FuturesPlaceOrderRequest) Quantity(quantity string) *FuturesPlaceOrderRequest {
	f.quantity = &quantity
	return f
}

/*
 * ReduceOnly sets
 */
func (f *FuturesPlaceOrderRequest) ReduceOnly(reduceOnly bool) *FuturesPlaceOrderRequest {
	f.reduceOnly = &reduceOnly
	return f
}

/*
 * Price sets
 */
func (f *FuturesPlaceOrderRequest) Price(price string) *FuturesPlaceOrderRequest {
	f.price = &price
	return f
}

/*
 * NewClientOrderId sets
 */
func (f *FuturesPlaceOrderRequest) NewClientOrderId(newClientOrderId string) *FuturesPlaceOrderRequest {
	f.newClientOrderId = &newClientOrderId
	return f
}

/*
 * NewOrderRespType sets
 */
func (f *FuturesPlaceOrderRequest) NewOrderRespType(newOrderRespType OrderRespType) *FuturesPlaceOrderRequest {
	f.newOrderRespType = &newOrderRespType
	return f
}

/*
 * PriceMatch sets
 */
func (f *FuturesPlaceOrderRequest) PriceMatch(priceMatch PriceMatchType) *FuturesPlaceOrderRequest {
	f.priceMatch = &priceMatch
	return f
}

/*
 * SelfTradePreventionMode sets
 */
func (f *FuturesPlaceOrderRequest) SelfTradePreventionMode(selfTradePreventionMode SelfTradePreventionModeType) *FuturesPlaceOrderRequest {
	f.selfTradePreventionMode = &selfTradePreventionMode
	return f
}

/*
 * GoodTillDate sets
 */
func (f *FuturesPlaceOrderRequest) GoodTillDate(goodTillDate int64) *FuturesPlaceOrderRequest {
	f.goodTillDate = &goodTillDate
	return f
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (f *FuturesPlaceOrderRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if f.isVarSlice(_v) {
			f.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (f *FuturesPlaceOrderRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check symbol field -> json key symbol
	symbol := f.symbol

	// TEMPLATE check-required
	if len(symbol) == 0 {
	}
	// END TEMPLATE check-required

	// assign parameter of symbol
	params["symbol"] = symbol
	// check side field -> json key side
	side := f.side

	// TEMPLATE check-required
	// END TEMPLATE check-required

	// assign parameter of side
	params["side"] = side
	// check positionSide field -> json key positionSide
	if f.positionSide != nil {
		positionSide := *f.positionSide

		// TEMPLATE check-required
		if len(positionSide) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch positionSide {
		case PositionSideLong, PositionSideShort, PositionSideBoth:
			params["positionSide"] = positionSide

		default:
			return nil, fmt.Errorf("positionSide value %v is invalid", positionSide)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of positionSide
		params["positionSide"] = positionSide
	} else {
	}
	// check orderType field -> json key type
	orderType := f.orderType

	// TEMPLATE check-required
	if len(orderType) == 0 {
	}
	// END TEMPLATE check-required

	// TEMPLATE check-valid-values
	switch orderType {
	case FuturesOrderTypeLimit, FuturesOrderTypeMarket:
		params["type"] = orderType

	default:
		return nil, fmt.Errorf("type value %v is invalid", orderType)

	}
	// END TEMPLATE check-valid-values

	// assign parameter of orderType
	params["type"] = orderType
	// check timeInForce field -> json key timeInForce
	if f.timeInForce != nil {
		timeInForce := *f.timeInForce

		// TEMPLATE check-required
		if len(timeInForce) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch timeInForce {
		case TimeInForceTypeGTC, TimeInForceTypeIOC, TimeInForceTypeFOK, TimeInForceTypeGTD, TimeInForceTypeGTX:
			params["timeInForce"] = timeInForce

		default:
			return nil, fmt.Errorf("timeInForce value %v is invalid", timeInForce)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of timeInForce
		params["timeInForce"] = timeInForce
	} else {
	}
	// check quantity field -> json key quantity
	if f.quantity != nil {
		quantity := *f.quantity

		// TEMPLATE check-required
		if len(quantity) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of quantity
		params["quantity"] = quantity
	} else {
	}
	// check reduceOnly field -> json key reduceOnly
	if f.reduceOnly != nil {
		reduceOnly := *f.reduceOnly

		// TEMPLATE check-required
		// END TEMPLATE check-required

		// assign parameter of reduceOnly
		params["reduceOnly"] = reduceOnly
	} else {
	}
	// check price field -> json key price
	if f.price != nil {
		price := *f.price

		// TEMPLATE check-required
		if len(price) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of price
		params["price"] = price
	} else {
	}
	// check newClientOrderId field -> json key newClientOrderId
	if f.newClientOrderId != nil {
		newClientOrderId := *f.newClientOrderId

		// TEMPLATE check-required
		if len(newClientOrderId) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of newClientOrderId
		params["newClientOrderId"] = newClientOrderId
	} else {
	}
	// check newOrderRespType field -> json key newOrderRespType
	if f.newOrderRespType != nil {
		newOrderRespType := *f.newOrderRespType

		// TEMPLATE check-required
		if len(newOrderRespType) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch newOrderRespType {
		case Ack, Result, Full:
			params["newOrderRespType"] = newOrderRespType

		default:
			return nil, fmt.Errorf("newOrderRespType value %v is invalid", newOrderRespType)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of newOrderRespType
		params["newOrderRespType"] = newOrderRespType
	} else {
	}
	// check priceMatch field -> json key priceMatch
	if f.priceMatch != nil {
		priceMatch := *f.priceMatch

		// TEMPLATE check-required
		if len(priceMatch) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch priceMatch {
		case PriceMatchNone, PriceMatchOpponent, PriceMatchOpponent5, PriceMatchOpponent10, PriceMatchOpponent20, PriceMatchQueue, PriceMatchQueue5, PriceMatchQueue10, PriceMatchQueue20:
			params["priceMatch"] = priceMatch

		default:
			return nil, fmt.Errorf("priceMatch value %v is invalid", priceMatch)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of priceMatch
		params["priceMatch"] = priceMatch
	} else {
	}
	// check selfTradePreventionMode field -> json key selfTradePreventionMode
	if f.selfTradePreventionMode != nil {
		selfTradePreventionMode := *f.selfTradePreventionMode

		// TEMPLATE check-required
		if len(selfTradePreventionMode) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch selfTradePreventionMode {
		case SelfTradePreventionModeExpireTaker, SelfTradePreventionModeExpireMaker, SelfTradePreventionModeExpireBoth, SelfTradePreventionModeNone:
			params["selfTradePreventionMode"] = selfTradePreventionMode

		default:
			return nil, fmt.Errorf("selfTradePreventionMode value %v is invalid", selfTradePreventionMode)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of selfTradePreventionMode
		params["selfTradePreventionMode"] = selfTradePreventionMode
	} else {
	}
	// check goodTillDate field -> json key goodTillDate
	if f.goodTillDate != nil {
		goodTillDate := *f.goodTillDate

		// TEMPLATE check-required

		if goodTillDate == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of goodTillDate
		params["goodTillDate"] = goodTillDate
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (f *FuturesPlaceOrderRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := f.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if f.isVarSlice(_v) {
			f.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (f *FuturesPlaceOrderRequest) GetParametersJSON() ([]byte, error) {
	params, err := f.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (f *FuturesPlaceOrderRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

var FuturesPlaceOrderRequestSlugReCache sync.Map

func (f *FuturesPlaceOrderRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		var needleRE *regexp.Regexp

		if cached, ok := FuturesPlaceOrderRequestSlugReCache.Load(_k); ok {
			needleRE = cached.(*regexp.Regexp)
		} else {
			needleRE = regexp.MustCompile(":" + _k + "\\b")
			FuturesPlaceOrderRequestSlugReCache.Store(_k, needleRE)
		}

		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (f *FuturesPlaceOrderRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (f *FuturesPlaceOrderRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (f *FuturesPlaceOrderRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := f.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (f *FuturesPlaceOrderRequest) GetPath() string {
	return "/fapi/v1/order"
}

// Do generates the request object and send the request object to the API endpoint
func (f *FuturesPlaceOrderRequest) Do(ctx context.Context) (*FuturesOrderResponse, error) {

	params, err := f.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	var apiURL string

	apiURL = f.GetPath()

	req, err := f.client.NewAuthenticatedRequest(ctx, "POST", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := f.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse FuturesOrderResponse

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return &apiResponse, nil
}
